# Generated by Django 2.2.4 on 2019-08-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190821_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userstatus',
            field=models.IntegerField(default=1),
        ),
    ]
