# Generated by Django 2.2.4 on 2019-08-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190822_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_type',
            field=models.IntegerField(default=1),
        ),
    ]
